"use client";
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { loadUIHistory, saveUIHistory } from "../../lib/ui-agent/persistence";
import { UIAgentQueue, emptyUIAgentState } from "../../lib/ui-agent/queue";
import { subscribeUIAgent } from "../../lib/ui-agent/events";
import type { UIAgentEvent, UIAgentState, VisualInspectionInput } from "../../lib/ui-agent/types";
interface Value extends UIAgentState { inspect:(input:VisualInspectionInput,event?:UIAgentEvent)=>boolean; }
const C=createContext<Value|null>(null); export function useUIAgent(){return useContext(C);}
export default function UIAgentProvider({children}:{children:React.ReactNode}){ const [state,setState]=useState<UIAgentState>(()=>{const h=loadUIHistory();return {...emptyUIAgentState(),active:true,inspected:h.inspected,recentFindings:h.findings,fixes:h.fixes};}); const [debug,setDebug]=useState(false); const queue=useMemo(()=>new UIAgentQueue((findings,event)=>setState(current=>{const next={...current,activeJobs:0,lastEvent:event,recentFindings:[...findings,...current.recentFindings].slice(0,80)};saveUIHistory({findings:next.recentFindings,fixes:next.fixes,inspected:next.inspected});return next;})),[]); const inspect=useCallback((input:VisualInspectionInput,event:UIAgentEvent={type:"visual-layout-changed",visualId:input.id,version:input.version,timestamp:Date.now()})=>{const version=input.version??JSON.stringify(input);let accepted=false;setState(current=>{if(current.inspected[`${input.id}:${version}`])return current;accepted=queue.enqueue(input.interactiveElements?"inspect-game":"inspect-visual",input,event);if(!accepted)return current;return {...current,activeJobs:queue.size,inspected:{...current.inspected,[`${input.id}:${version}`]:Date.now()},lastEvent:event};});return accepted;},[queue]); useEffect(()=>subscribeUIAgent(event=>setState(current=>({...current,lastEvent:event}))),[]); useEffect(()=>{if(typeof window!=="undefined")setDebug(new URLSearchParams(window.location.search).has("ui-agent")||process.env.NODE_ENV!=="production");},[]); const value=useMemo(()=>({...state,inspect}),[inspect,state]); return <C.Provider value={value}>{children}{debug&&<Status/>}</C.Provider>; }
function Status(){const a=useUIAgent();const [open,setOpen]=useState(true);const [pos,setPos]=useState({x:16,y:16});const [drag,setDrag]=useState<{x:number;y:number;px:number;py:number}|null>(null);useEffect(()=>{if(!drag)return;const move=(e:MouseEvent)=>setPos(p=>({x:Math.max(8,p.x+e.clientX-drag.px),y:Math.max(8,p.y+e.clientY-drag.py)}));const up=()=>setDrag(null);window.addEventListener("mousemove",move);window.addEventListener("mouseup",up);return()=>{window.removeEventListener("mousemove",move);window.removeEventListener("mouseup",up)}},[drag]);if(!a||!open)return null;const warnings=a.recentFindings.filter(f=>f.severity!=="info"&&!f.resolvedAt).length;return <aside aria-label="UI Guardian status" className="ui-agent-status" style={{right:"auto",bottom:"auto",left:pos.x,top:pos.y}}><div className="flex cursor-move items-center gap-2" onMouseDown={e=>setDrag({x:pos.x,y:pos.y,px:e.clientX,py:e.clientY})}><span className="ui-agent-dot" aria-hidden="true"/><strong>UI Guardian</strong><span className="text-xs opacity-70">Active</span><button type="button" aria-label="Close UI Guardian" className="ml-auto rounded px-1 text-base leading-none opacity-70 hover:opacity-100" onMouseDown={e=>e.stopPropagation()} onClick={()=>setOpen(false)}>×</button></div><div className="mt-2 grid grid-cols-3 gap-2 text-center text-[10px]"><span><b className="block text-sm">{a.recentFindings.filter(f=>f.severity==="critical").length}</b>critical</span><span><b className="block text-sm">{warnings}</b>warnings</span><span><b className="block text-sm">{a.fixes.length}</b>fixes</span></div>{a.recentFindings.slice(0,3).map(f=><p key={f.id} className="mt-2 border-t border-current/10 pt-1 text-[10px]">{f.message}</p>)}</aside>}
